### ISSUE TITLE
Craft 4 Version

### ISSUE THREAD

**Issue by CreateSean** [vardump-de/recentchanges#2]
Do you have plans to release a Craft 4 compatible version of this plugin?

**Comment by engram-design** [comment]
Just to chime in, we've added this to our [Craft 3 migration project](https://verbb.io/craft-3). If it gets enough votes, we'll migrate this plugin to Craft 4 and continue to work on it, giving it a new home, and keeping it open source.

Do let us know if you plan to make the plugin Craft 4 compatible!

**Comment by rmdev** [comment]
yes, we have it on our list, but unfortunately there is little time at the moment. It will take a few weeks, before its done.

**Comment by CreateSean** [comment]
Any update on this?

**Comment by rmdev** [comment]
hey, i have worked on it, but it needs some testing before release, i think. 
I just pushed the current state. feel free to test.

**Comment by CreateSean** [comment]
Is there a specific command to install a beta?

**Comment by rmdev** [comment]
you can install it via composer: 
`composer require vardump/recentchanges:craft4-dev`

**Comment by rmdev** [comment]
Ups, forgot to close this issue.
Craft 4 version released 2022-12-07: 
https://github.com/vardump-de/recentchanges/releases/tag/2.0.0
